// Code generated by core tool ; DO NOT EDIT.

package enum

/** OSタイプ */
type (
	OsType int64
)

const (
	/** iOS */
	OsType_IOS OsType = 1
	/** Android */
	OsType_ANDROID OsType = 2
	/** 全て */
	OsType_OS_ALL OsType = 9
)

var _OsTypeMap = map[OsType]struct{}{
	OsType_IOS:     struct{}{},
	OsType_ANDROID: struct{}{},
	OsType_OS_ALL:  struct{}{},
}

// Within Enumとしてその値が含まれているか
func (t OsType) Within() bool {
	_, ok := _OsTypeMap[t]
	return ok
}

func (t OsType) Int64() int64 {
	return int64(t)
}

func (t OsType) String() string {
	switch t {
	case OsType_IOS:
		return "IOS"
	case OsType_ANDROID:
		return "ANDROID"
	case OsType_OS_ALL:
		return "OS_ALL"
	default:
		return "Unknown"
	}
}
